Update srcds1

diff --git a/Dedicated Server Fresh Start/srcds1 b/Dedicated Server Fresh Start/srcds1
--- a/Dedicated Server Fresh Start/srcds1
+++ b/Dedicated Server Fresh Start/srcds1
@@ -1,14 +1,14 @@
 #!/bin/bash
-
+set -x
 # replace "steam" with the user you created, leave it alone if you've actually called your user "steam"
-SRCDS_USER="steam"
+SRCDS_USER="eric"
 
 # Do not change this path
 PATH=/bin:/usr/bin:/sbin:/usr/sbin
 
 # The path to the game, only change this if you have a different installation path than in the guide.
-DIR=/home/steam/Steam/steamapps/common/l4d2
-DAEMON="$DIR/srcds_run"
+DIR=/home/eric/l4d2
+DAEMON="srcds_run"
 
 # Change all Parameters to your needs.
 
@@ -34,12 +34,20 @@ DAEMON="$DIR/srcds_run"
 
 # The current settings will start the Server on 100 Tick on Dead Center 1.
 SVNUM=1
-IP=1.3.3.7
+IP=192.168.1.22
 PORT=27015
 NAME=L4D2_Server$SVNUM
-PARAMS="-game left4dead2 -ip $IP -port $PORT +sv_clockcorrection_msecs 15 -timeout 10 -tickrate 100 +map c1m1_hotel -maxplayers 32 +servercfgfile server$SVNUM.cfg"
+SRCDS_DIR_STEAMCMD="$HOME/steamcmd"
+SRCDS_STEAM_FILES="l4d2_update.txt"
+SRCDS_FORCE_DIR="$HOME/${SRCDS_FOLDER_NAME}"
+PARAMS="-game left4dead2 -console -ip $IP -port $PORT +sv_clockcorrection_msecs 15 -timeout 10 -tickrate 100 -maxplayers 16 -nowatchdog -sv_pure 2 +servercfgfile server$SVNUM.cfg"
 DESC="L4D2 Dedicated Server #$SVNUM on port $PORT"
 
+
+if [[ "$(whoami)" == root ]]; then
+  echo -e "Sorry, you can't run this"
+  exit 1
+fi
 
 ###########################################
 #                                         #
@@ -52,7 +60,7 @@ case "$1" in
 		echo "Starting $DESC: $NAME"
 		if [ -e $DIR ]; then
 			cd $DIR
-			su $SRCDS_USER -l -c "screen -AdmS $NAME -L screenlog.0  $DAEMON $PARAMS"
+			su $SRCDS_USER -l -c "screen -AdmS $NAME -L screenlog.0 ./$DAEMON $PARAMS"
 		else
 			echo "No such directory: $DIR!"
 		fi
@@ -71,14 +79,15 @@ case "$1" in
 	restart)
 		if su $SRCDS_USER -l -c "screen -ls" |grep $NAME; then
 			echo -n "Stopping $DESC: $NAME"
-			kill `su $SRCDS_USER -l -c "screen -ls" |grep $NAME |awk -F . '{print $1}'|awk '{print $1}'`
+			#kill `su $SRCDS_USER -l -c "screen -ls" |grep $NAME |awk -F . '{print $1}'|awk '{print $1}'`
+			screen -dr l4d2_$SVNUM -X quit
 			echo " ... done."
 		else
 			echo "Couldn't find a running $DESC"
 		fi
 		echo -n "Starting $DESC: $NAME"
 		cd $DIR
-		su $SRCDS_USER -l -c "screen -d -m -S $NAME $DAEMON $PARAMS"
+		screen -AmdS -L screenlog.0 l4d2_$SVNUM $PARAMS
 		echo " ... done."
 		;;
 
